// Generated by CoffeeScript 1.9.1
var Lastfeed, parsers, providerIdMatch, url;

url = require('url');

parsers = require('../parser');

providerIdMatch = function(parserId, providerId) {
  return providerId.indexOf(parserId, providerId.length - parserId.length) !== -1;
};

Lastfeed = (function() {
  function Lastfeed(config) {
    var i, len, parser;
    this.config = config;
    this.providerId = url.parse(this.config.url).host;
    this.feedId = this.config.url.replace(/^http:\/\//, '').replace(/[\/|\.]/g, '-');
    this.feedCacheKey = "feed:cache:" + this.feedId;
    this.feedRawKey = "feed:raw:" + this.feedId;
    this.feedConfigKey = "config:" + this.feedId;
    this.parser = null;
    for (i = 0, len = parsers.length; i < len; i++) {
      parser = parsers[i];
      if (providerIdMatch(parser.id, this.providerId)) {
        this.parser = parser;
        break;
      }
    }
    if (parser === null) {
      throw new Error("Cant found parser for " + this.providerId);
    }
  }

  return Lastfeed;

})();

module.exports = Lastfeed;
