// Generated by CoffeeScript 1.9.1
var LastError;

LastError = (function() {
  function LastError(message, details, innerError) {
    this.message = message;
    this.details = details;
    this.innerError = innerError;
  }

  return LastError;

})();

module.exports = LastError;
