// Generated by CoffeeScript 1.9.1
var LastfeedBag;

LastfeedBag = (function() {
  function LastfeedBag(config) {
    this.config = config;
  }

  LastfeedBag.prototype.getConfigKey = function() {
    return "config:" + this.config.id;
  };

  LastfeedBag.prototype.getFeedCacheKey = function() {};

  LastfeedBag.prototype.getFeedRawKey = function() {};

  return LastfeedBag;

})();
