// Generated by CoffeeScript 1.9.1
var ameblo, blogspot, dotblogs;

ameblo = require('./ameblo-parser');

blogspot = require('./blogspot-parser');

dotblogs = require('./dotblogs-parser');

module.exports = [ameblo, blogspot, dotblogs];
