// Generated by CoffeeScript 1.9.3
var ameblo, blogspot, dotblogs, nichcn;

ameblo = require('./ameblo-parser');

blogspot = require('./blogspot-parser');

dotblogs = require('./dotblogs-parser');

nichcn = require('./2chcn-parser');

module.exports = [ameblo, blogspot, dotblogs, nichcn];
