// Generated by CoffeeScript 1.9.1
var FeedParser, Lastfeed, checkFeedUpdates, cheerio, client, co, completeFeedPosts, configs, coreq, fs, lastfeedTask, loadConfiguation, monitor, parser, redis, request, setCachedFeed;

request = require('request');

FeedParser = require('feedparser');

co = require('co');

fs = require('mz/fs');

coreq = require('co-request');

cheerio = require('cheerio');

redis = require('redis');

client = redis.createClient();

monitor = redis.createClient();

Lastfeed = require('./lib/lastfeed');

parser = require('./parser');

configs = null;

monitor.psubscribe('*config:*');

monitor.on('pmessage', function(pattern, channel, message) {
  if (message !== 'del' && message !== 'set') {
    return;
  }
  console.log(message);
  console.log(channel);
  return console.log(configs);
});

loadConfiguation = function*() {
  var getAllConfigKeys, getConfigByKey, i, k, keys, len;
  getAllConfigKeys = function() {
    return new Promise(function(resolve, reject) {
      return client.keys('config:*', function(err, replies) {
        if (err != null) {
          return reject(err);
        } else {
          return resolve(replies);
        }
      });
    });
  };
  getConfigByKey = function(key) {
    return new Promise(function(resolve, reject) {
      return client.get(key, function(err, reply) {
        var config, e;
        if (err != null) {
          return reject(err);
        } else {
          try {
            config = JSON.parse(reply);
            return resolve(config);
          } catch (_error) {
            e = _error;
            return reject(e);
          }
        }
      });
    });
  };
  keys = (yield getAllConfigKeys());
  configs = [];
  for (i = 0, len = keys.length; i < len; i++) {
    k = keys[i];
    configs.push((yield getConfigByKey(k)));
  }
  return configs;
};

setCachedFeed = function(cacheKey, feedText) {
  console.log("caching...");
  console.log(cacheKey);
  return client.set(cacheKey, feedText);
};

checkFeedUpdates = function*(lastfeed) {
  var cachedFeedText, feed, feedText, feedUpdated, promiseGetCachedRawFeed, promiseGetFeed;
  promiseGetCachedRawFeed = function(lastfeed) {
    return new Promise(function(resolve, reject) {
      var feedKey;
      console.log("111");
      console.log(lastfeed);
      feedKey = lastfeed.getFeedRawKey();
      console.log(feedKey);
      return client.get(feedKey, function(err, reply) {
        if (err != null) {
          console.log(err);
          return reject(err);
        } else {
          return resolve(reply);
        }
      });
    });
  };
  promiseGetFeed = function(lastfeed) {
    return new Promise(function(resolve, reject) {
      var feed, feedparser, req, url;
      console.log("1");
      url = lastfeed.config.url;
      req = request(url);
      feedparser = new FeedParser();
      console.log("2");
      feed = {};
      feed.meta = null;
      feed.articles = [];
      req.on('error', function(error) {
        return reject(error);
      });
      req.on('response', function(resp) {
        if (resp.statusCode !== 200) {
          this.emit('error', new Error('Bad status code'));
        }
        return this.pipe(feedparser);
      });
      feedparser.on('error', function(error) {
        return reject(error);
      });
      feedparser.on('readable', function() {
        var post, results;
        results = [];
        while (post = this.read()) {
          results.push(feed.articles.push(post));
        }
        return results;
      });
      feedparser.on('meta', function(meta) {
        return feed.meta = meta;
      });
      feedparser.on('end', function() {
        return resolve(feed);
      });
      return console.log("3");
    });
  };
  feed = (yield promiseGetFeed(lastfeed));
  console.log(5);
  feedText = JSON.stringify(feed);
  console.log("12");
  cachedFeedText = (yield promiseGetCachedRawFeed(lastfeed));
  console.log(6);
  if (cachedFeedText === feedText) {
    feedUpdated = false;
  } else {
    feedUpdated = true;
  }
  return {
    feed: feed,
    feedUpdated: feedUpdated
  };
};

completeFeedPosts = function*(lastfeed) {
  var article, feedCacheString, i, len, postText, postUrl, ref, resp;
  ref = lastfeed.feed.articles;
  for (i = 0, len = ref.length; i < len; i++) {
    article = ref[i];
    postUrl = article.link;
    console.log(postUrl);
    resp = (yield coreq(postUrl));
    postText = parser.ameblo.parse(resp.body);
    article.description = postText;
  }
  console.log("cache feed");
  feedCacheString = JSON.stringify(lastfeed.feed);
  setCachedFeed(lastfeed.getFeedCacheKey(), feedCacheString);
  return console.log("cached");
};

lastfeedTask = function*(lastfeed) {
  var feedText, value;
  value = (yield checkFeedUpdates(lastfeed));
  lastfeed.feed = value.feed;
  lastfeed.rawfeed = value.feed;
  lastfeed.feedUpdated = value.feedUpdated;
  if (lastfeed.feedUpdated) {
    console.log("try cache to file");
    value = (yield completeFeedPosts(lastfeed));
    console.log("set raw cache");
    feedText = JSON.stringify(lastfeed.rawfeed);
    setCachedFeed(lastfeed.getFeedRawKey(), feedText);
    console.log("completeFeedPosts: " + value);
  }
  return lastfeed;
};

co(function*() {
  var lastfeed;
  configs = (yield loadConfiguation());
  lastfeed = new Lastfeed(configs[0]);
  lastfeed = (yield lastfeedTask(lastfeed));
  return lastfeed;
}).then(function(lastfeed) {
  console.log("fin");
  console.log("feedUpdated: " + lastfeed);
  return client.end();
}, function(error) {
  console.log(error);
  return console.log("error on parse fedd");
});
